### ISSUE TITLE
Links have a lot of weird margin left and right

### ISSUE THREAD

**Issue by keks** [socketsupply/tonic-docs#10]
The links on tonicframework.dev look weird:

![image](https://user-images.githubusercontent.com/146678/177142856-ce8f8678-6af6-4d44-a5f5-c14fd2489bd1.png)

**Comment by keks** [comment]
I am on Chromium 102 on Linux, but I've first noticed this a while ago

**Comment by lamiazar** [comment]
This issue is now fixed. thank you @keks
